services:
  db:
    image: postgres:16-alpine
    container_name: docslite-db
    environment:
      POSTGRES_USER: docs
      POSTGRES_PASSWORD: docs
      POSTGRES_DB: docs
    ports:
      - '5432:5432'
    volumes:
      - docsdb:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docs -d docs']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  docsdb: {}
